package org.stvad.kask.model.generator

import com.squareup.kotlinpoet.FileSpec
import com.squareup.moshi.Moshi
import org.stvad.kask.InvalidModelException
import org.stvad.kask.model.IntentDefinition
import org.stvad.kask.model.InteractionModelEnvelope
import org.stvad.kask.model.jsonAdapter
import java.io.File

object KaskGenerator {
    private const val fileName = "intents"
    private const val generatedNotificationComment =
            "This code is generated by the Kask model generation plugin. Any changes made would be overridden during next build."

    fun generateAlexaModel(packageName: String, modelPath: File, outputPath: File) {
        val intentDefinitions = getIntentDefinitions(modelPath)

        val intents = FileSpec.builder(packageName, fileName).apply {
            intentDefinitions.map { IntentGenerator(it).generate() }.forEach { addType(it) }
        }
        IntentGenerator.requiredImports.forEach { intents.addImport(it.first, it.second) }

        intents.addComment(generatedNotificationComment)
                .build()
                .writeTo(outputPath)
    }

    private fun getIntentDefinitions(modelPath: File): List<IntentDefinition> {
        val interactionModelEnvelope =
                InteractionModelEnvelope.jsonAdapter(Moshi.Builder().build()).fromJson(modelPath.readText())
                        ?: throw InvalidModelException("The supplied alexa language model is not valid")

        return interactionModelEnvelope.interactionModel.languageModel.intentDefinitions
    }
}